version: '2'
services:
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=password
    volumes:
      - ./.data/db:/var/lib/mysql
    ports:
      - 3306:3306
  web:
    image: lthub/moodle:medicine
    build: .
    ports:
      - 8080:80
    # use the links section if you want to use a container for a database.
    # if not, and you want to use an external database server, configure
    # if with the environment variables in the 'environment' section.
    # see README.md for more details.
    links:
      - db
    # uncomment the 'volumes' section to enable a shared volume with docker-compose
    volumes:
      - ./.data/web:/moodledata:rw
      # do not uncomment this when starting a new instance from scratch as
      # init script won't be able to move this file
      #- ./LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      - SERVER_NAME=localhost
      - MOODLE_DB_TYPE=mariadb
      - MOODLE_DB_HOST=db
      #- MOODLE_DB_PORT=
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodle
      - MOODLE_DB_PASSWORD=password
      - MOODLE_DB_PREFIX=
      - MOODLE_URL=http://localhost:8080
      #- MOODLE_SITE_FULLNAME=
      #- MOODLE_SITE_SHORTNAME=
      #- MOODLE_SITE_LANG=
      #- MOODLE_ADMIN_USER=
      #- MOODLE_ADMIN_PASS=
      #- MOODLE_ADMIN_EMAIL=
      #- MOODLE_UPDATE=
      #- MOODLE_SSL_PROXY=false
      - MOODLE_REDIS_HOST=redis
      - MOODLE_REDIS_PORT=6379
      - MOODLE_REDIS_DB=0
      #- MOODLE_REDIS_PREFIX=''
      - MOODLE_DISABLE_UPDATE_AUTODEPLOY=true
      #- MOODLE_DEBUG=true
      #- MOODLE_SMTP_HOST=example.com:465
      #- MOODLE_SMTP_USER=test
      #- MOODLE_SMTP_PASS=testpass
      #- MOODLE_SMTP_SECURITY=ssl
      #- MOODLE_SMTP_AUTH_TYPE=PLAIN
      #- MOODLE_NOREPLY_ADDRESS=test@example.com
      - SHIBBOLETH_IDP_DISCOVERY_URL=https://dev.ubccpd.ca
      - SHIBBOLETH_IDP_METADATA_URL=https://dev.ubccpd.ca/simplesaml/saml2/idp/metadata.php
      - SHIBBOLETH_IDP_ENTITY_ID=https://dev.ubccpd.ca/simplesaml/saml2/idp/metadata.php
      - SHIBBOLETH_SP_ENTITY_ID=https://moodle.ubc.ca
      - SHIBD_LISTENER_ACL=0.0.0.0/0
      - SHIBD_ODBC_DRIVER=MySql
      - SHIBD_ODBC_LIB=odbc-store.so
      - SHIBD_ODBC_SERVER=db
      - SHIBD_ODBC_PORT=3306
      - SHIBD_ODBC_DATABASE=moodle
      - SHIB_ODBC_USER=moodle
      - SHIB_ODBC_PASSWORD=password
      - SHIBD_ATTRIBUTE_MAP_URL=
      - SHIBD_SERVICE_NAME=shibd
      - SHIBD_SERVICE_PORT=1600
      - PHP_MEMORY_LIMIT=256M
  redis:
    image: redis:5.0-alpine
    volumes:
      - ./.data/redis:/data
    ports:
      - 6379:6379
  shibd:
    image: lthub/shibd
    environment:
      - SHIBBOLETH_IDP_DISCOVERY_URL=https://dev.ubccpd.ca
      - SHIBBOLETH_IDP_METADATA_URL=https://dev.ubccpd.ca/simplesaml/saml2/idp/metadata.php
      - SHIBBOLETH_IDP_ENTITY_ID=https://dev.ubccpd.ca/simplesaml/saml2/idp/metadata.php
      - SHIBBOLETH_SP_ENTITY_ID=https://moodle.ubc.ca
      - SHIBD_LISTENER_ACL=0.0.0.0/0
      - SHIBD_LISTENER_ADDRESS=0.0.0.0
      - SHIBD_ODBC_DRIVER=MySql
      - SHIBD_ODBC_LIB=odbc-store.so
      - SHIBD_ODBC_SERVER=db
      - SHIBD_ODBC_PORT=3306
      - SHIBD_ODBC_DATABASE=moodle
      - SHIB_ODBC_USER=moodle
      - SHIB_ODBC_PASSWORD=password
      - SHIBD_ATTRIBUTE_MAP_URL=
    volumes:
      - ./.data/cert:/etc/shibboleth/cert:rw